### ISSUE TITLE
I found an error when the value of the request header value is "zh-CN,zh;q=0.9".

### ISSUE THREAD

**Issue by xmm1229** [litespeedtech/ls-hpack#10]
I found an error when the value of the request header value is "zh-CN,zh;q=0.9".

headkey: "Accept-Language",
headvalue: "zh-CN,zh;q=0.9"

===========================displayHeader==============================
408b 8484 2d69 5b38 ea9a d1cc 5f8c f73a |
d7b4 fd7b 9fef b400 5dff
===========================printTable===========================
Dynamic Table :
[62] `Accept-Language' = `zh-CN,zh;q=0.9'
----------------------step for [recvReq01]----------------

Assertion failed: rc == 0

**Comment by litespeedtech** [comment]
header name need to be all lowercase.

**Comment by xmm1229** [comment]
> header name need to be all lowercase.

Thank you, problem solved.

However, the root cause is that I use strlen to calculate bufEnd.
unsigned char *bufEnd = bufSamp + strlen((const char *)bufSamp);

If the value of headkey is "accept-language", the value of headvalue is "zh-CN,zh;q=0.9", and the encode result is 518c f73a d7b4 fd7b 9fef b400 5dff, "\0" in the result will cause an incorrect strlen result.

Sorry for this issue.
