### ISSUE TITLE
add xxhash.c into ls-hpack library to simplify dependent programs build

### ISSUE THREAD

**Issue by alexpokotilo** [litespeedtech/ls-hpack#5]
Hi,
if I build ls-hpack library running

> cmake -DCMAKE_BUILD_TYPE=Release .

and then try to build simple program that use it running

> g++ main.c -I "./include" -L "./" -lls-hpack

I get

> 
> .//libls-hpack.a(lshpack.c.o): In function `lshpack_enc_encode':
> lshpack.c:(.text+0x70f): undefined reference to `XXH32_reset'
> lshpack.c:(.text+0x72b): undefined reference to `XXH32_update'
> lshpack.c:(.text+0x733): undefined reference to `XXH32_digest'
> lshpack.c:(.text+0x752): undefined reference to `XXH32_update'
> lshpack.c:(.text+0x75a): undefined reference to `XXH32_digest'

I understand(and see in library examples) that I can build ./deps/xxhash/xxhash.c as part of my executable but may be we can add ./deps/xxhash/xxhash.c into ls-hpack library to simplify building dependent programs ?

I temporary added this to my CMakeList.txt
IF (SHARED EQUAL 1)
    ADD_LIBRARY(ls-hpack SHARED src/lshpack.c ./deps/xxhash/xxhash.c)
ELSE()
    ADD_LIBRARY(ls-hpack STATIC src/lshpack.c ./deps/xxhash/xxhash.c)
ENDIF()

and it works fine and I just include ls-hpack library. I understand that xxhash.c is external lib and may be used in target project as well. But we can introduce an option disabled by default  to include xxhash.c into lshpack lib.
If it's ok I can create pull request

**Comment by dtikhonov** [comment]
> may be we can add ./deps/xxhash/xxhash.c into ls-hpack library to simplify building dependent programs?

We sure can: we already do this in [ls-qpack's CMakeLists.txt](
https://github.com/litespeedtech/ls-qpack/blob/master/CMakeLists.txt), but haven't gotten around to ls-hpack yet.

> If it's ok I can create pull request

A pull request would be much appreciated -- thank you!

**Comment by alexpokotilo** [comment]
Hi @dtikhonov,
I've filed #6 pull request. Default behavior remain the same but if we add _-DLSHPACK_XXH:=TRUE_
live

> cmake -DCMAKE_BUILD_TYPE=Release -DLSHPACK_XXH:=TRUE 

we will get deps/xxhash/xxhash.c included as the library target.
Please let me know once approved/merged so I can switch to master.
Thanks for great library BTW!

**Comment by dtikhonov** [comment]
Thanks for the PR -- it has been merged.

As for the library: you're welcome! If you use it in a project, we'd like to hear about it.

**Comment by alexpokotilo** [comment]
@dtikhonov,
thanks for fast request processing.
Not to advertise my project but just because you asked:
We(I'm representing softvelum.com) are adding httpv2 support to our "Nimble Streamer"(c) server.
I found **ls-hpack** library and added it to our project development branch. It's just a start point to add v2 support but it was important first step to find proper rfc7541 implementation with permissive license. If you want us to add **LiteSpeed** to our docs once v2 support released or add something to our site or discuss any matters please contact us via https://wmspanel.com/help

My current integration plan(when we release v2 support) is to add **ls-hpack** LICENSE file into Nimble docs. Please contact provided url if you want us to add blog post, mention in our materials or things like that to provide deserved respect to LiteSpeed.
Thanks again!

**Comment by dtikhonov** [comment]
Yours looks like an interesting product.  Good luck with HTTP/2.

Have you considered HTTP/3?  I know of a [good library that supports it](https://github.com/litespeedtech/lsquic)...

If you want to blog or tweet about ls-hpack, we will of course be only glad.
